= gyaric
:toc:
:sectnums:

image:https://github.com/jiro4989/gyaric/workflows/build/badge.svg[Build Status]

gyaric is a module to encode/decode text to unreadable gyaru's text.

This is a joke module. `decode` proc has problems.

== Overview

Japanese gyaru sometimes do not use regular hiragana or katakana when chatting
with text. Instead of using regular hiragana or katakana, they express hiragana
and katakana with symbols that approximate them. I don't know the reason that
they do it, but maybe they want to make the text cute.

This module provides to encode regular hiragana or katakana text to unreadable
gyaru's text, and decode that.

== What is the gyaru?

A girl who dies her hair blonde or brown, wears a lot of make up, wears short
skirts, carries brand-name bags, is fun to be with and speaks casually.

== Installation

[source,bash]
----
nimble install gyaric
----

== Usage

=== Library

[source,nim]
----
import gyaric

echo gyaric.encode("あいうえお")
# -> ァﾚヽ⊃`λ_寸>`

echo gyaric.decode(gyaric.encode("あいうえお"))
# -> あいうえお

echo gyaric.encode("彼氏があたしにだまって浮気してたかもしんないの・・・。しんじらんない・・・")
# -> 彼氏ｶヾァ+ﾆυ｜=ﾅ＝ﾞмаッ〒浮気υ〒+ﾆヵゝм○υｗ+ョﾚ|σ・・・。υｗUﾞζｗ+ョﾚ|・・・
----

=== CLI

[source,bash]
----
$ gyaric encode <<< あいうえお
ァﾚヽ⊃`λ_寸>`

$ gyaric decode <<< ァﾚヽ⊃`λ_寸>`
あいうえお

$ gyaric encode <<< 彼氏があたしにだまって浮気してたかもしんないの・・・。しんじらんない・・・
彼氏ｶヾァ+ﾆυ｜=ﾅ＝ﾞмаッ〒浮気υ〒+ﾆヵゝм○υｗ+ョﾚ|σ・・・。υｗUﾞζｗ+ョﾚ|・・・
----

== Documents

* https://jiro4989.github.io/gyaric/gyaric.html[gyaric]

== LICENSE

MIT
